### ISSUE TITLE
BLACK-ISORT linter fails on Windows when black==24.1.1 and Python==3.9

### ISSUE THREAD

**Issue by justinchuby** [justinchuby/lintrunner-adapters#93]
This linter processes the file with isort before sending the result to black as `input` to the subprocess.

In https://github.com/justinchuby/lintrunner-adapters/blob/c9727c9c5369722e56d54764770c5118ac72e950/lintrunner_adapters/adapters/black_isort_linter.py#L42-L58, the `input` argument was somehow not taken by `black` when `black==24.1.1` on Windows, Python 3.8/Python 3.9.

Maybe consider pipeline the results instead and send it via stdin?

**Comment by guotuofeng** [comment]
do we try stdin?

**Comment by justinchuby** [comment]
It is still failing even after switching to stdin. I am not sure what is going on.

**Comment by justinchuby** [comment]
It has to be run within lintrunner, _and_ python 3.9, _and_ black==24.1.1, _and_ Windows. Somehow the interaction among these tools and platforms caused the behavior. Does lintrunner set stdin on Windows the interfered with the tools? But only on Windows with Python 3.8/3.9?

**Comment by justinchuby** [comment]
I am trying to debug with black to make sure stdin is not empty when accepted by black, but I haven't been able to set breakpoints in black in my current environment. I am not sure which installation it was using.

**Comment by justinchuby** [comment]
I suspect black somehow failed to recognize there's stuff in stdin under certain conditions.

**Comment by guotuofeng** [comment]
what about run the black-linter only without running the isort_linter?

**Comment by guotuofeng** [comment]
I tried only run black-linter, it seems the error still happens. so this may indicate the input is not the root cause.

**Comment by guotuofeng** [comment]
[input.txt](https://github.com/justinchuby/lintrunner-adapters/files/14159550/input.txt)

Please run 
``bash
python -m lintrunner_adapters run black_isort_linter -- @d:\third_party\lintrunner\input.txt
```

You would have similar output like:

![image](https://github.com/justinchuby/lintrunner-adapters/assets/817030/565d9d48-b360-4746-9226-21432b21093b)

**Comment by guotuofeng** [comment]
![image](https://github.com/justinchuby/lintrunner-adapters/assets/817030/a65e615a-0db3-4a8f-91c9-599dac746e60)

**Comment by guotuofeng** [comment]
https://github.com/psf/black/issues/4209 is created.

**Comment by justinchuby** [comment]
Thanks for the investigation! Good catch that I didn’t actually look into the path files and forgot they were different.
